{% set version = "0.6.1" %}

package:
  name: isodate
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/isodate/isodate-{{ version }}.tar.gz
  sha256: 48c5881de7e8b0a0d648cb024c8062dc84e7b840ed81e864c7614fd3c127bde9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - six
  run:
    - python
    - six

test:
  imports:
    - isodate
    - isodate.tests

about:
  home: http://cheeseshop.python.org/pypi/isodate
  license: BSD 3-Clause
  summary: An ISO 8601 date/time/duration parser and formatter.
  description: |
    This module implements ISO 8601 date, time and duration parsing. The
    implementation follows ISO8601:2004 standard, and implements only date/time
    representations mentioned in the standard.
  dev_url: https://github.com/gweis/isodate

extra:
  recipe-maintainers:
    - ocefpaf
